const mongoose = require('mongoose')

var routerSchema = new mongoose.Schema({
    FuelTypeCode:{type: String},
    StationName:{type: String},
    StreetAddress:{type: String},
    IntersectionDirections:{type: String},
    City:{type: String},
    State:{type: String},
    ZIP:{type: String},
    Plus4:{type: String},
    StationPhone:{type: String},
    StatusCode:{type:String},
    ExpectedDate:{type: String},
    GroupsWithAccessCode:{type: String},
    AccessDaysTime:{type: String},
    CardsAccepted:{type: String},
    BDBlends:{type: String},
    NGFillTypeCode:{type: String},
    NGPSI:{type: String},
    EVLevel1EVSENum:{type: String},
    EVLevel2EVSENum:{type: String},
    EVDCFastCount:{type: String},
    EVOtherInfo:{type: String},
    EVNetwork:{type: String},
    EVNetworkWeb:{type: String},
    GeocodeStatus:{type: String},
    Latitude:{type: String},
    Longitude:{type: String},
    DateLastConfirmed:{type: String},
    ID:{type: String},
    UpdatedAt:{type: String},
    OwnerTypeCode:{type: String},
    FederalAgencyID:{type: String},
    FederalAgencyName:{type: String},
    OpenDate:{type: String},
    HydrogenStatusLink:{type: String},
    NGVehicleClass:{type: String},
    LPGPrimary:{type: String},
    E85BlenderPump:{type: String},
    EVConnectorTypes:{type: String},
    Country:{type: String},
    IntersectionDirectionsFrench:{type: String},
    AccessDaysTimeFrench:{type: String},
    BDBlendsFrench:{type: String},
    GroupsWithAccessCodeFrench:{type: String},
    HydrogenIsRetail:{type: String},
    AccessCode:{type: String},
    AccessDetailCode:{type: String},
    FederalAgencyCode:{type: String},
    FacilityType:{type: String},
    CNGDispenserNum:{type: String},
    CNGOnSiteRenewableSource:{type: String},
    CNGTotalCompressionCapacity:{type: String},
    CNGStorageCapacity:{type: String},
    LNGOnSiteRenewableSource:{type: String},
    E85OtherEthanolBlends:{type: String},
    EVPricing:{type: String},
    EVPricingFrench:{type: String},
    LPGNozzleTypes:{type: String},
    HydrogenPressures:{type: String},
    HydrogenStandards:{type: String},
    CNGFillTypeCode:{type: String},
    CNGPSI:{type: String},
    CNGVehicleClass:{type: String},
    LNGVehicleClass:{type: String},
    EVOnSiteRenewableSource:{type: String},
    RestrictedAccess:{type: String},

});

mongoose.model("Routes", routerSchema);
